version: "3.3"

x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/pangolin.svg
  urls:
    - https://docs.pangolin.net/manage/sites/understanding-sites#newt-site-recommended

services:
  newt:
    container_name: newt
    image: fosrl/newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT
      - NEWT_ID
      - NEWT_SECRET
    networks:
      - exposed-external
    labels:
      # glance
      glance.category: other
      glance.name: Newt
      glance.icon: di:pangolin
      glance.description: Proxy Tunnel

networks:
  exposed-external:
    name: exposed-external
    external: true
