services:
  newt:
    image: fosrl/newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT
      - NEWT_ID
      - NEWT_SECRET
    networks:
      - exposed-external

networks:
  exposed-external:
    name: exposed-external
    external: true
