services:
  sonarr:
    image: ghcr.io/hotio/sonarr
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/sonarr:/config
      - /arr-stack/data:/data
    networks:
      - exposed-internal
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=111
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8989/tcp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.sonarr.rule=Host(`sonarr.mnemosyne.lan`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.entrypoints=web

  radarr:
    image: ghcr.io/hotio/radarr
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/radarr:/config
      - /arr-stack/data:/data
    networks:
      - exposed-internal
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=111
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=7878/tcp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.radarr.rule=Host(`radarr.mnemosyne.lan`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.entrypoints=web

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/qbittorrent:/config
      - /arr-stack/data/torrents:/data/torrents
    networks:
      - exposed-internal
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=222
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp
      - LIBTORRENT=v1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.mnemosyne.lan`)
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
      - traefik.http.routers.qbittorrent.entrypoints=web

  sabnzbd:
    image: ghcr.io/hotio/sabnzbd
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/sabnzbd:/config
      - /arr-stack/data/usenet:/data/usenet
    networks:
      - exposed-internal
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=333
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.mnemosyne.lan`)
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
      - traefik.http.routers.sabnzbd.entrypoints=web

  jellyfin:
    image: ghcr.io/hotio/jellyfin
    volumes:
      - /arr-stack/config/jellyfin:/config
      - /arr-stack/data/media:/data/media
    networks:
      - exposed-internal
      - exposed-external
    environment:
      - PUID=444
      - PGID=321
      - UMASK=002
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.sabnzbd.rule=Host(`jellyfin.jsmarier.com`)
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8096
      - traefik.http.routers.sabnzbd.entrypoints=web

networks:
  exposed-internal:
    external: true
  exposed-external:
    external: true
