version: "3.3"

x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/servarr.svg
  urls:
    - https://wiki.servarr.com/

services:
  sonarr-en:
    container_name: sonarr-en
    image: ghcr.io/hotio/sonarr
    hostname: sonarr-en.internal
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/sonarr/en:/config
      - /arr-stack/data:/data
    networks:
      - exposed-internal
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=111
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8989/tcp
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.sonarr-en.rule: Host(`sonarr-en.mnemosyne.lan`)
      traefik.http.services.sonarr-en.loadbalancer.server.port: 8989
      traefik.http.routers.sonarr-en.entrypoints: web
      traefik.http.routers.sonarr-en.tls: true
      # arcane
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/sonarr.svg

  sonarr-fr:
    container_name: sonarr-fr
    image: ghcr.io/hotio/sonarr
    hostname: sonarr-fr.internal
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/sonarr/fr:/config
      - /arr-stack/data:/data
    networks:
      - exposed-internal
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=111
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8989/tcp
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.sonarr-fr.rule: Host(`sonarr-fr.mnemosyne.lan`)
      traefik.http.services.sonarr-fr.loadbalancer.server.port: 8989
      traefik.http.routers.sonarr-fr.entrypoints: web
      traefik.http.routers.sonarr-fr.tls: true
      # arcane
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/sonarr.svg

  radarr-en:
    container_name: radarr-en
    image: ghcr.io/hotio/radarr
    hostname: radarr-en.internal
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/radarr/en:/config
      - /arr-stack/data:/data
    networks:
      - exposed-internal
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=222
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=7878/tcp
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.radarr-en.rule: Host(`radarr-en.mnemosyne.lan`)
      traefik.http.services.radarr-en.loadbalancer.server.port: 7878
      traefik.http.routers.radarr-en.entrypoints: web
      traefik.http.routers.radarr-en.tls: true
      # arcane
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/radarr.svg

  radarr-fr:
    container_name: radarr-fr
    image: ghcr.io/hotio/radarr
    hostname: radarr-fr.internal
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/radarr/fr:/config
      - /arr-stack/data:/data
    networks:
      - exposed-internal
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=222
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=7878/tcp
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.radarr-fr.rule: Host(`radarr-fr.mnemosyne.lan`)
      traefik.http.services.radarr-fr.loadbalancer.server.port: 7878
      traefik.http.routers.radarr-fr.entrypoints: web
      traefik.http.routers.radarr-fr.tls: true
      # arcane
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/radarr.svg

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    hostname: prowlarr.internal
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/prowlarr:/config
      - /arr-stack/data:/data
    networks:
      - exposed-internal
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=333
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=9696/tcp
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.mnemosyne.lan`)
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
      traefik.http.routers.prowlarr.entrypoints: web
      traefik.http.routers.prowlarr.tls: true
      # arcane
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/prowlarr.svg

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    hostname: qbittorrent.internal
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/qbittorrent:/config
      - /arr-stack/data/torrents:/data/torrents
    networks:
      - exposed-internal
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=444
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp
      - LIBTORRENT=v1
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent.mnemosyne.lan`)
      traefik.http.services.qbittorrent.loadbalancer.passhostheader: true
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      traefik.http.routers.qbittorrent.entrypoints: web
      traefik.http.routers.qbittorrent.tls: true
      # arcane
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/qbittorrent.svg

  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd
    hostname: sabnzbd.internal
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/sabnzbd:/config
      - /arr-stack/data/usenet:/data/usenet
    networks:
      - exposed-internal
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=555
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.sabnzbd.rule: Host(`sabnzbd.mnemosyne.lan`)
      traefik.http.services.sabnzbd.loadbalancer.server.port: 8080
      traefik.http.routers.sabnzbd.entrypoints: web
      traefik.http.routers.sabnzbd.tls: true
      # arcane
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/sabnzbd.svg

  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    hostname: jellyfin.internal
    cap_add:
      - NET_ADMIN
    volumes:
      - /arr-stack/config/jellyfin:/config
      - /arr-stack/data/media:/data/media
    networks:
      - exposed-internal
      - exposed-external
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=pia
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_PORT_REDIRECTS
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS
      # - VPN_INTERFACE_PREFIXES
      - VPN_PIA_USER
      - VPN_PIA_PASS
      # - VPN_PIA_PREFERRED_REGION
      # - VPN_PIA_DIP_TOKEN
      - VPN_PIA_PORT_FORWARD_PERSIST=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
      # - UNBOUND_NAMESERVERS
      # --- Basic --- #
      - PUID=666
      - PGID=321
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8096/tcp
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.docker.network: exposed-internal
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.mnemosyne.lan`)
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      traefik.http.routers.jellyfin.entrypoints: web
      traefik.http.routers.jellyfin.tls: true
      # arcane
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/jellyfin.svg

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    hostname: flaresolverr.internal
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - PROMETHEUS_ENABLED=true
      - PROMETHEUS_PORT=8192
    networks:
      - exposed-internal
    labels:
      # arcane
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/flaresolverr.svg

networks:
  exposed-internal:
    external: true
  exposed-external:
    external: true
