version: "3.3"

x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/grafana.svg
  urls:
    - https://grafana.com/docs/grafana/latest/

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    hostname: grafana.internal
    restart: unless-stopped
    volumes:
      - /volumes/monitoring/grafana:/var/lib/grafana
    networks:
      - exposed-internal
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.grafana.rule: Host(`grafana.jsmarier.dev`)
      traefik.http.routers.grafana.entrypoints: websecure
      traefik.http.routers.grafana.tls: true
      traefik.http.routers.grafana.tls.certresolver: cloudflare
      traefik.http.services.grafana.loadbalancer.server.port: 3000

      # glance
      glance.category: monitoring
      glance.name: Grafana
      glance.icon: di:grafana
      glance.url: https://grafana.jsmarier.dev/
      glance.description: Monitoring dashboards

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus.internal
    restart: unless-stopped
    volumes:
      - /volumes/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - /volumes/monitoring/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    networks:
      - exposed-internal
    labels:
      # arcane
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/prometheus.svg

      # glance
      glance.category: monitoring
      glance.name: Prometheus
      glance.icon: di:prometheus
      glance.url: https://prometheus.jsmarier.dev/
      glance.description: Monitoring data scraping

networks:
  exposed-internal:
    name: exposed-internal
    external: true
