version: "3.3"

x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/grafana.svg
  urls:
    - https://grafana.com/docs/grafana/latest/

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    hostname: grafana.internal
    restart: unless-stopped
    volumes:
      - /monitoring/grafana:/var/lib/grafana
    networks:
      - exposed-internal
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.grafana.rule: Host(`grafana.mnemosyne.lan`)
      traefik.http.services.grafana.loadbalancer.server.port: 3000
      traefik.http.routers.grafana.entrypoints: web
      traefik.http.routers.grafana.tls: true

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus.internal
    restart: unless-stopped
    volumes:
      - /monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - /monitoring/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    networks:
      - exposed-internal
    labels:
      # arcane
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/prometheus.svg

networks:
  exposed-internal:
    name: exposed-internal
    external: true
